# Test 2026-05-31 at 17:16:45

name: Copy Paste Detection

on:
  push:
    paths:
      - '**/cpd.yml'

jobs:
  cpd:
    name: Run Copy/Paste Detection
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: 'JDK'
        uses: oracle-actions/setup-java@v1

      - name: Install PMD
        run: |
          PMD_VERSION=7.24.0
          wget -q https://github.com/pmd/pmd/releases/download/pmd_releases%2F${PMD_VERSION}/pmd-dist-${PMD_VERSION}-bin.zip
          unzip pmd-dist-${PMD_VERSION}-bin.zip
          mv pmd-bin-$PMD_VERSION pmd
          echo "$PWD/pmd-bin-${PMD_VERSION}/bin" >> $GITHUB_PATH

      - name: Run CPD (Copy/Paste Detector)
        run: |
          tree

      - name: Run CPD (Copy/Paste Detector)
        run: |
          ./pmd/bin/pmd cpd --minimum-tokens 50  --language java --dir . --format text --no-fail-on-error --no-fail-on-violation --report-file cpd-report.txt

      - name: Show CPD Report
        run: cat cpd-report.txt

      - name: Upload CPD Report
        uses: actions/upload-artifact@v4
        with:
          name: cpd-report
          path: cpd-report.txt
