# 2026-08-28 at 20:04:43
# Install OpenRam in two containers to create identical environments locally and on github

run-name: Docker Open Ram

on:
  push:
    paths:
      - '**/dockerOpenRam.yml'

jobs:
  build:
    permissions:
      contents: read
      packages: write                                                                                                   # Needed for GHCR push

    runs-on: ubuntu-latest

    steps:
    - name: Checkout code
      uses: actions/checkout@v4

  test:
    needs: build
    if: github.event_name == 'push' && needs.build.result == 'success'
    runs-on: ubuntu-latest

    container:
      image: ghcr.io/${{ github.repository_owner }}/or_local:latest
      options: --privileged --user=root

    permissions:
      contents: write

    steps:
    - name: Checkout code
      uses: actions/checkout@v4

    - name: Test gitHub version of container
      run: |
        pip3 show openram
