# 2026-09-07 at 18:07:101
# Install OpenRam in two containers to create identical environments locally and on github

run-name: Docker Open Ram

on:
  push:
    paths:
      - '**/dockerOpenRam.yml'

jobs:

  build_github:
    permissions:
      contents: read
      packages: write                                                                                                   # Needed for GHCR push

    runs-on: ubuntu-latest

    steps:
    - name: Checkout code
      uses: actions/checkout@v4

    - name: github - Create Docker file
      run: |
        useradd --uid 1001  --gid 1001  --non-unique  --create-home  --home-dir /home/phil  --shell /bin/bash  phil
        whoami
        id
