# Test 2026-08-12 at 13:34:07

name: Docker Silicon Compiler
run-name: btreeList

on:
  push:
    paths:
      - '**/dockerSiliconCompiler.yml'

jobs:
  build:
    permissions:
      contents: read
      packages: write                                                                                                   # Needed for GHCR push

    runs-on: ubuntu-latest

    steps:
    - name: Checkout code
      uses: actions/checkout@v4
    - name: local - Install base packages
      run: |
        cat << 'EOF' > Dockerfile
        FROM ubuntu:latest

        ENV DEBIAN_FRONTEND=noninteractive
        ENV TZ=Etc/UTC

        RUN apt-get update  -qq && apt-get install -qq -y tzdata python3-dev python3-pip python3-venv curl git build-essential sudo   iverilog openjdk-25-jdk-headless tree yosys gh; rm -rf /var/lib/apt/lists/*

        RUN usermod -l phil ubuntu && groupmod -n phil ubuntu && usermod -d /home/phil -m phil && echo "phil ALL=(ALL) NOPASSWD:ALL" > /etc/sudoers.d/phil
        USER phil
        WORKDIR /home/phil

        RUN python3 -m venv ./sc; ./sc/bin/pip install --upgrade pip && ./sc/bin/pip install siliconcompiler && ./sc/bin/sc-install openroad klayout yosys sv2v netgen opensta verible &&  rm -rf .cache .sc/tool_build .stack

        ENV PATH=/home/phil/sc/bin:/home/phil/.local/bin/:/usr/local/sbin:/usr/local/bin:/usr/sbin:/usr/bin:/sbin:/bin
        CMD ["/bin/bash", "--login"]
        EOF

    - name: local - log in to GitHub Container Registry
      uses: docker/login-action@v2
      with:
        registry: ghcr.io
        username: ${{ github.actor }}
        password: ${{ secrets.GITHUB_TOKEN }}

    - name: local - Build Docker image
      run: |
        docker build -t ghcr.io/philiprbrenan/sc_local:latest .

    - name: local - push Docker image to GHCR
      run: |
        docker push ghcr.io/philiprbrenan/sc_local:latest
    - name: github - Install base packages
      run: |
        cat << 'EOF' > Dockerfile
        FROM ubuntu:latest

        ENV DEBIAN_FRONTEND=noninteractive
        ENV TZ=Etc/UTC

        RUN apt-get update  -qq && apt-get install -qq -y tzdata python3-dev python3-pip python3-venv curl git build-essential sudo   iverilog openjdk-25-jdk-headless tree yosys gh; rm -rf /var/lib/apt/lists/*

        RUN usermod -l phil ubuntu && groupmod -n phil ubuntu && usermod -d /home/phil -m phil && echo "phil ALL=(ALL) NOPASSWD:ALL" > /etc/sudoers.d/phil
        USER phil
        WORKDIR /home/phil

        RUN python3 -m venv ./sc; ./sc/bin/pip install --upgrade pip && ./sc/bin/pip install siliconcompiler && ./sc/bin/sc-install openroad klayout yosys sv2v netgen opensta verible &&  rm -rf .cache .sc/tool_build .stack

        ENV PATH=/home/phil/sc/bin:/home/phil/.local/bin/:/usr/local/sbin:/usr/local/bin:/usr/sbin:/usr/bin:/sbin:/bin
        CMD ["/bin/bash", "--login"]
        EOF

    - name: github - log in to GitHub Container Registry
      uses: docker/login-action@v2
      with:
        registry: ghcr.io
        username: ${{ github.actor }}
        password: ${{ secrets.GITHUB_TOKEN }}

    - name: github - Build Docker image
      run: |
        docker build -t ghcr.io/philiprbrenan/sc_github:latest .

    - name: github - push Docker image to GHCR
      run: |
        docker push ghcr.io/philiprbrenan/sc_github:latest
  test:
    needs: build
    if: github.event_name == 'push' && needs.build.result == 'success'
    runs-on: ubuntu-latest

    container:
      image: ghcr.io/philiprbrenan/sc_github:latest
      options: --privileged --user=phil

    permissions:
      contents: write

    steps:
    - name: Show identities
      run: |
        id
        id phil
        ls -ld /__w

    - name: Checkout code
      uses: actions/checkout@v4

    - name: test container
      run: |
        pip show siliconcompiler
        python3 -c 'import siliconcompiler; print(siliconcompiler.__version__)'
