# Test 2026-05-06 at 16:31:22

name: Test
run-name: btreeList

on:
  push:
    paths:
      - '**/main.yml'

#concurrency:
#  group: ${{ github.workflow }}-${{ github.ref }}
# cancel-in-progress: true

jobs:

  test:
    permissions: write-all
    runs-on: ubuntu-latest

    strategy:
      matrix:
        task: [BitSet, Program, Test, Tree]

    steps:
    - uses: actions/checkout@v4
      with:
        ref: 'main'

    - name: 'JDK'
      uses: oracle-actions/setup-java@v1

    - name: Verilog install
      run: |
        sudo apt install iverilog yosys tree

    - name: Position files in package
      run: |
        mkdir -p com/AppaApps/Silicon
        cp BitSet.java Program.java Test.java Tree.java com/AppaApps/Silicon
        tree

    - name: Java
      run: |
        javac -g -d Classes -cp Classes com/AppaApps/Silicon/*.java

    - name: Test BitSet
      if: matrix.task == 'BitSet'
      run: |
        java -XX:+UseZGC -cp Classes com/AppaApps/Silicon/BitSet


    - name: Test Program
      if: matrix.task == 'Program'
      run: |
        java -XX:+UseZGC -cp Classes com/AppaApps/Silicon/Program


    - name: Test Test
      if: matrix.task == 'Test'
      run: |
        java -XX:+UseZGC -cp Classes com/AppaApps/Silicon/Test


    - name: Test Tree
      if: matrix.task == 'Tree'
      run: |
        java -XX:+UseZGC -cp Classes com/AppaApps/Silicon/Tree

