# Test 2026-06-22 at 00:52:23

name: Test
run-name: btreeList

on:
  push:
    paths:
      - '**/main.yml'

#concurrency:
#  group: ${{ github.workflow }}-${{ github.ref }}
# cancel-in-progress: true

jobs:

  test:
    permissions: write-all
    runs-on: ubuntu-latest

    strategy:
      matrix:
        task: [BitSet, Branch, Leaf, Program, Slots, Test, Tree]

    steps:
    - uses: actions/checkout@v4
      with:
        ref: 'main'

    - name: 'JDK'
      uses: oracle-actions/setup-java@v1

    - name: Verilog install
      run: |
        sudo apt install iverilog yosys tree
        mkdir -p verilog


    - name: Position files in package
      run: |
        mkdir -p com/AppaApps/Silicon
        cp BitSet.java Branch.java Leaf.java Program.java Slots.java Test.java Tree.java com/AppaApps/Silicon
        tree

    - name: Java
      run: |
        javac -g -d Classes -cp Classes com/AppaApps/Silicon/*.java

    - name: Test BitSet
      if: ${{ always() && matrix.task == 'BitSet' }}
      run: |
        java -XX:+UseZGC -cp Classes com/AppaApps/Silicon/BitSet

    - name: Zip files
      if: ${{ always() && matrix.task == 'BitSet' }}
      run: |
        mv verilog/ BitSet-sverilog/
        zip -r BitSet-sverilog.zip BitSet-sverilog/

    - name: Upload artifact
      if: ${{ always() && matrix.task == 'BitSet' }}
      uses: actions/upload-artifact@v4
      with:
        name: BitSet-sverilog
        path: BitSet-sverilog.zip

    - name: Test Branch
      if: ${{ always() && matrix.task == 'Branch' }}
      run: |
        java -XX:+UseZGC -cp Classes com/AppaApps/Silicon/Branch

    - name: Zip files
      if: ${{ always() && matrix.task == 'Branch' }}
      run: |
        mv verilog/ Branch-sverilog/
        zip -r Branch-sverilog.zip Branch-sverilog/

    - name: Upload artifact
      if: ${{ always() && matrix.task == 'Branch' }}
      uses: actions/upload-artifact@v4
      with:
        name: Branch-sverilog
        path: Branch-sverilog.zip

    - name: Test Leaf
      if: ${{ always() && matrix.task == 'Leaf' }}
      run: |
        java -XX:+UseZGC -cp Classes com/AppaApps/Silicon/Leaf

    - name: Zip files
      if: ${{ always() && matrix.task == 'Leaf' }}
      run: |
        mv verilog/ Leaf-sverilog/
        zip -r Leaf-sverilog.zip Leaf-sverilog/

    - name: Upload artifact
      if: ${{ always() && matrix.task == 'Leaf' }}
      uses: actions/upload-artifact@v4
      with:
        name: Leaf-sverilog
        path: Leaf-sverilog.zip

    - name: Test Program
      if: ${{ always() && matrix.task == 'Program' }}
      run: |
        java -XX:+UseZGC -cp Classes com/AppaApps/Silicon/Program

    - name: Zip files
      if: ${{ always() && matrix.task == 'Program' }}
      run: |
        mv verilog/ Program-sverilog/
        zip -r Program-sverilog.zip Program-sverilog/

    - name: Upload artifact
      if: ${{ always() && matrix.task == 'Program' }}
      uses: actions/upload-artifact@v4
      with:
        name: Program-sverilog
        path: Program-sverilog.zip

    - name: Test Slots
      if: ${{ always() && matrix.task == 'Slots' }}
      run: |
        java -XX:+UseZGC -cp Classes com/AppaApps/Silicon/Slots

    - name: Zip files
      if: ${{ always() && matrix.task == 'Slots' }}
      run: |
        mv verilog/ Slots-sverilog/
        zip -r Slots-sverilog.zip Slots-sverilog/

    - name: Upload artifact
      if: ${{ always() && matrix.task == 'Slots' }}
      uses: actions/upload-artifact@v4
      with:
        name: Slots-sverilog
        path: Slots-sverilog.zip

    - name: Test Test
      if: ${{ always() && matrix.task == 'Test' }}
      run: |
        java -XX:+UseZGC -cp Classes com/AppaApps/Silicon/Test

    - name: Zip files
      if: ${{ always() && matrix.task == 'Test' }}
      run: |
        mv verilog/ Test-sverilog/
        zip -r Test-sverilog.zip Test-sverilog/

    - name: Upload artifact
      if: ${{ always() && matrix.task == 'Test' }}
      uses: actions/upload-artifact@v4
      with:
        name: Test-sverilog
        path: Test-sverilog.zip

    - name: Test Tree
      if: ${{ always() && matrix.task == 'Tree' }}
      run: |
        java -XX:+UseZGC -cp Classes com/AppaApps/Silicon/Tree

    - name: Zip files
      if: ${{ always() && matrix.task == 'Tree' }}
      run: |
        mv verilog/ Tree-sverilog/
        zip -r Tree-sverilog.zip Tree-sverilog/

    - name: Upload artifact
      if: ${{ always() && matrix.task == 'Tree' }}
      uses: actions/upload-artifact@v4
      with:
        name: Tree-sverilog
        path: Tree-sverilog.zip
